### PR TITLE
Add back ./run

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add back ./run

## QA
- Run `./run clean`
- Run `./run`
- Run `./run test`
- All the above should be successful

### CODE REVIEW

**Comment by sparkiegeek** [comment]
Why was it removed? How does it relate to [`dotrun`](https://snapcraft.io/dotrun) ?

**Comment by anthonydillon** [comment]
`dotrun` is the snap version @lilyvidenova want to be able to check the UI on her host quickly. This is just a stop gap before to move fully `dotrun`.

**Comment by lilyvidenova** [comment]
@anthonydillon when I do ./run and try to access MAAS at localhost:8400/MAAS I get his output in the console

image
and this in terminal
image

**Comment by anthonydillon** [comment]
That's a strange error. Did it complete and show you an IP when you ran `./run`? We my bed to pair on it to get it working.

**Comment by lilyvidenova** [comment]
I think so:
image

**Comment by anthonydillon** [comment]
Yeah looks good, hmm... Let's pair tomorrow and see if we can work it out.

**Comment by lilyvidenova** [comment]
Sounds good, whenever you can @anthonydillon

**Comment by huwshimi** [comment]
@lilyvidenova I can see what the problem is and can reproduce it myself, I've filed https://github.com/canonical-web-and-design/maas-ui/issues/910 and will try and fix that today.

I believe this is a different issue and this PR QAs fine for me. @lilyvidenova do please comment on that bug I've filed if you see differently.

**Comment by huwshimi** [comment]
@lilyvidenova I have a PR for this issue: https://github.com/canonical-web-and-design/maas-ui/pull/911. I should have mentioned that this will resolve those errors, but not your issue with access the VPN from your multipass. I seem to remember resolving this in the past with the help of your email from Oct 15 titled "Multipass and VPN".

**Comment by lilyvidenova** [comment]
@huwshimi The resolution from this email doesn't work for me anymore, nor do the solutions on their discourse :( I will submit an issue and see if someone can help me but at the same time, I'd rather be able to just run the UI on my mac!

**Pull request merged**
