### PR TITLE
Run labeler action on cron.

### PR DESCRIPTION
**Pull request by squidsoup**
See https://github.com/actions/labeler/issues/12#issuecomment-525762657

### CODE REVIEW

**Comment by Caleb-Ellis** [comment]
@squidsoup looks like running it on a cron job won't actually work? https://github.com/actions/labeler/issues/12#issuecomment-526207828

**Comment by squidsoup** [comment]
> actions/labeler#12 (comment)

Ugh, well I guess we just keep this around until they've figured out a solution for forks.

**Comment by Caleb-Ellis** [comment]
Iceboxing for now until the upstream issue is resolved.

**Comment by squidsoup** [comment]
Closing this since we've removed the labeller action for now. If they fix actions/labeler#12 (comment) we can revisit this.

**Pull request closed without merging**
