### PR TITLE
refactor(ui): update notification to use a slice

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Replace the notification actions and reducers with a slice.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Check that you can see and dismiss notifications (I used `make harness` to create some notifications).

## Fixes

Fixes: canonical-web-and-design/maas-ui#1658

### CODE REVIEW

**Comment by huwshimi** [comment]
@Caleb-Ellis I've updated this to `dismiss` now.

**Review by Caleb-Ellis — CHANGES_REQUESTED** [review]
Clicking "Dismiss all" on a notification group disconnects the websocket. Leftover `delete` maybe?

**Comment by huwshimi** [comment]
> Clicking "Dismiss all" on a notification group disconnects the websocket. Leftover `delete` maybe?

Yep you were right, not sure how I missed that. Fixed now.

**Review by Caleb-Ellis — APPROVED** [review]
LGTM!

**Pull request merged**
