### PR TITLE
Build tag form and tag selector components.

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done
- Built `TagSelector` component which allows selecting existing tags and creating new tags.
- Built `TagForm` component.

## QA
- Select some machines and choose "Tag" from action dropdown
- Check that you can do the following things:
  - [ ] select tags from dropdown
  - [ ] remove selected tags
  - [ ] filter tags based on what's typed
  - [ ] create a new tag if what's typed does not exist
  - [ ] try creating a new tag with spaces, and check that the spaces are replaced with dashes

## Fixes
Fixes canonical-web-and-design/MAAS-squad#1786
Fixes canonical-web-and-design/MAAS-squad#1832

### Default
Screenshot_2020-04-02 Machines karura MAAS

### Open
Screenshot_2020-04-02 Machines karura MAAS(3)

### Selected
Screenshot_2020-04-02 Machines karura MAAS(4)

### New tag
Screenshot_2020-04-02 Machines karura MAAS(5)

### CODE REVIEW

**Comment by huwshimi** [comment]
@Caleb-Ellis one QA thing:
- If you create a tag with a space it gives an error when you submit the form. In the angular version it creates the tag and replaces spaces with dashes.

**Comment by Caleb-Ellis** [comment]
Good catch @huwshimi, that should be fixed now

**Comment by Caleb-Ellis** [comment]
@huwshimi or else what?!?!?! Was I close to death without even realising?

**Comment by huwshimi** [comment]
@Caleb-Ellis it's too late, you'll never know.

**Pull request merged**
