### PR TITLE
feat(proxy): dev console messages

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Display message when loading clients in the console.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Run `dotrun` or `yarn start`.
- At the start you should see a red message about waiting for the clients to load.
- After all the clients have started you should see a message with the URL to load.
- Visiting that URL should show you the app.
- Run `dotrun ui` or `yarn ui`.
- Shortly you should see a message about waiting for the React client to load.
- When it loads visit the URL and the app should be ready.

## Fixes

Fixes: #858.

### CODE REVIEW

**Review by Caleb-Ellis — COMMENTED** [review]
This is a bit fancy! I did notice there were a ton of `wait until bundle is finished` messages that didn't show up before? It doesn't make anything slower or change anything really but it's a bit weird. Do you think we should not be auto-opening a window if the message shows the correct address now?

**Comment by huwshimi** [comment]
> This is a bit fancy! I did notice there were a ton of `wait until bundle is finished` messages that didn't show up before? It doesn't make anything slower or change anything really but it's a bit weird.

Yeah I think thats from `wait-on` polling the url to see if it's ready and the server rejecting it (maybe from the proxy). I don't really think we can do anything about the warnings, but we might be able to filter out them out from being displayed.

> Do you think we should not be auto-opening a window if the message shows the correct address now?

We could, but maybe I'm just old and grumpy but I find those things a bit annoying, I usually already have a tab for the UI open and then I have to go to all the trouble of closing the tab that opens, IT RUINS MY DAY.

**Comment by Caleb-Ellis** [comment]
> Yeah I think thats from wait-on polling the url to see if it's ready and the server rejecting it (maybe from the proxy). I don't really think we can do anything about the warnings, but we might be able to filter out them out from being displayed.

That must be it. Could filter them out as a follow-up but it's probably not worth the effort, plus the (minimal) added risk of filtering out something we actually want to show.

> We could, but maybe I'm just old and grumpy but I find those things a bit annoying, I usually already have a tab for the UI open and then I have to go to all the trouble of closing the tab that opens, IT RUINS MY DAY.

Nah I feel the same way, and it's impossible that we're *both* old and grumpy so it must just actually be annoying!

**Review by Caleb-Ellis — APPROVED** [review]

**Comment by huwshimi** [comment]
> > Yeah I think thats from wait-on polling the url to see if it's ready and the server rejecting it (maybe from the proxy). I don't really think we can do anything about the warnings, but we might be able to filter out them out from being displayed.
> 
> That must be it. Could filter them out as a follow-up but it's probably not worth the effort, plus the (minimal) added risk of filtering out something we actually want to show.

I had a quick look and it's single-spa that's showing the errors, but I can't see any simple way to silence them.

**Pull request merged**
