### PR TITLE
feat(legacy): allow disabling boot architectures in subnet details

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Backport of https://github.com/canonical-web-and-design/maas-ui/pull/2677

### CODE REVIEW

**Review by huwshimi — APPROVED** [review]

**Comment by anthonydillon** [comment]
Is there an issue for this? If not can you add an Epic, Sprint, Estimate and Milestone please.

**Comment by Caleb-Ellis** [comment]
@anthonydillon this is just a backport of https://github.com/canonical-web-and-design/MAAS-squad/issues/2400 from `master` to `3.0`

Do you think we need an issue for each backport?

**Comment by anthonydillon** [comment]
Maybe, if it takes time and would be useful to have stats on backports. It doesn't need an issue but the meta data in the PR should be enough to represent it in the reports.

What you think?

**Comment by Caleb-Ellis** [comment]
Yeah that's fair, probably just a 1 pointer though

**Pull request merged**
