### PR TITLE
feat(ui): add link to workload annotations discourse page

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Replaced placeholder docs link for workload annotations

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to the machine details page of an Allocated or Deployed machine
- Click the "Read more" link in the Workloads card
- Check that it takes you to a discourse page (which is currently empty, but will have content by 2.10 release)

## Fixes

Fixes canonical-web-and-design/MAAS-squad#2304

### CODE REVIEW

**Comment by anthonydillon** [comment]
This post is private? Can we get a public link?

**Comment by Caleb-Ellis** [comment]
@anthonydillon according to [this](https://github.com/canonical-web-and-design/MAAS-squad/issues/2304#issuecomment-785226514) the post will be made public once it's set up a bit, but we would consider it "done" on our end

**Comment by anthonydillon** [comment]
I just don't think it's worth making it private in case we forgot to make it public.

**Review by huwshimi — APPROVED** [review]

**Comment by anthonydillon** [comment]
Just a reminder, this post is still private.

**Pull request merged**
