### PR TITLE
refactor: sort jsx props alphabetically

### PR DESCRIPTION
**Pull request by petermakowski**
## Done

-  sort jsx props alphabetically via `react/jsx-sort-props`

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Steps for QA.

## Fixes

Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/3314

## Launchpad issue

Related Launchpad maas issue in the form `lp#number`.

## Backports

In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate releases to target.

Only bug and security fixes should be backported, new features should only land in master.

### CODE REVIEW

**Review by anthonydillon — COMMENTED** [review]
Thanks @petermakowski. What is the benefit of doing this? Will this auto fix via Pettier? I don't want to slow anyone down for none practical reasons.

**Comment by petermakowski** [comment]
> Thanks @petermakowski. What is the benefit of doing this? Will this auto fix via Pettier? I don't want to slow anyone down for none practical reasons.

Yeah, this is fixed automatically on save / via `lint --fix`. It's just something that we were doing in MAAS anyway and will mean less time spent in code reviews on discussing details such as this as it'll be automated.

**Comment by Caleb-Ellis** [comment]
This is probably safe to land now that we've split off a branch for 3.2, but I wonder if we should wait just a little longer until 3.2 proper comes out in case we need to backport some fixes from master (which might mean conflicts)? Or maybe that's being overly cautious....

**Comment by petermakowski** [comment]
> This is probably safe to land now that we've split off a branch for 3.2, but I wonder if we should wait just a little longer until 3.2 proper comes out in case we need to backport some fixes from master (which might mean conflicts)? Or maybe that's being overly cautious....

This isn't of high priority and touches a lot of files, let's wait. 👍

**Comment by huwshimi** [comment]
> > This is probably safe to land now that we've split off a branch for 3.2, but I wonder if we should wait just a little longer until 3.2 proper comes out in case we need to backport some fixes from master (which might mean conflicts)? Or maybe that's being overly cautious....
> 
> This isn't of high priority and touches a lot of files, let's wait. 👍

Seeing as we've rearranged the whole codebase we can probably land this one too. It may end up being easier to run `--fix` again as I've broken this pretty badly for you. Sorry!

**Comment by petermakowski** [comment]
This is now ready for review @Caleb-Ellis / @huwshimi

**Review by huwshimi — APPROVED** [review]
Looks good! I didn't review this line-by-line.

It's nice that this respects props after a spread so that it doesn't break things that get deliberately overwritten.

**Pull request merged**
