### PR TITLE
docs(shared): update the docs lnks in the footer to the offline docs

### PR DESCRIPTION
**Pull request by anthonydillon**
The offline docs are not provided by the MAAS itself. This change links to the offline docs from the
footer links. This change does not include all docs links across the UI.

Fixes https://github.com/canonical-web-and-design/MAAS-squad/issues/2125

## Done

- Itemised list of what was changed by this PR.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps
**Two ways**
- Build a new maas containing the offline docs and run this UI, scroll to the footer and click the two links to docs
- Run locally and click the docs links. Once they load switch the base URL to bolla.internal. For example: http://bolla.internal:5240/MAAS/docs/maas-documentation-25.html

## Backports
N/A

### CODE REVIEW

**Review by squidsoup — COMMENTED** [review]
master is essentially 2.9, but this appears to be linking to documentation for 2.8?

I'm not sure I love that we're going to have to update these links for every release, as that seems like something we're likely to forget. Could these files have names that aren't specific to a release, so we don't need to update the footer?

**Comment by anthonydillon** [comment]
Yeah I agree, there are a few improvements to offline docs which I'm filing issues for. I have requested a permanent whats-on location so it's correct for any version installed.

**Comment by anthonydillon** [comment]
@cristinadresch why was this assigned to me?

**Comment by cristinadresch** [comment]
> @cristinadresch why was this assigned to me?

We thought maybe you were looking into a solution for a 'dynamic' link that works across releases?

**Comment by anthonydillon** [comment]
There is no solution for now. I have filed the bugs for these to be addressed. This PR either needs to be rejected or accepted and updated when versions are released.

**Comment by cristinadresch** [comment]
@anthonydillon cool, I've assigned it to @Caleb-Ellis for review

**Comment by Caleb-Ellis** [comment]
@anthonydillon This should probably be pointing at the 2.8 branch instead of master, right? Are there already links for 2.9 docs?

**Comment by anthonydillon** [comment]
I think for now I should just update the footer link to a single like to offline docs. That will get around this issue.

**Comment by anthonydillon** [comment]
@Caleb-Ellis I have updated the footer links to remove the release notes link for now. Once we have a solution for https://bugs.launchpad.net/maas/+bug/1898680.

**Comment by squidsoup** [comment]
Thanks for filing that bug @anthonydillon

**Review by squidsoup — APPROVED** [review]

**Pull request merged**
