### PR TITLE
fix(ui): get betterer working again

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Update betterer to 4.0.1 to get it working again.

## QA

N/A CI should pass

## Fixes

Fixes: #2296.

### CODE REVIEW

**Comment by anthonydillon** [comment]
CI is still failing.

**Review by anthonydillon — CHANGES_REQUESTED** [review]
CI is failing

**Comment by huwshimi** [comment]
> CI is failing

But I fixed it! :(

**Comment by huwshimi** [comment]
@anthonydillon looks like it really is fixed this time.

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
