### PR TITLE
LP: #1861952 - Allow special characters in usernames and passwords.

### LINKED ISSUE #751: Cannot login using password with '+' character
https://bugs.launchpad.net/maas/+bug/1861952

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done
- Encode credentials when making fetch login request

## QA
- Create a user with special characters (+ - _ etc) in their name and confirm you can log in as them
- Create a user with special characters in their password and confirm you can log in as them

## Fixes
Fixes #751 

## Launchpad Issue
LP: #1861952

### CODE REVIEW

**Comment by sparkiegeek** [comment]
Did you consider using `URLSearchParams` for the `body` instead?

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

**Comment by anthonydillon** [comment]
@Caleb-Ellis can you write some tests to cover the bug use-cases please

**Comment by Caleb-Ellis** [comment]
Thanks @anthonydillon I've added an extra issue for the test here: https://github.com/canonical-web-and-design/maas-ui/issues/753

It's gonna take me a while to remember how to use redux sagas/redux-saga-test-plan and I'd prefer to merge this sooner rather than later.

**Comment by anthonydillon** [comment]
Ok sure. 👍

**Pull request merged**
