### PR TITLE
refactor(ui): convert DoubleRow and TableMenu to typescript

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Convert DoubleRow and TableMenu to typescript.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- View the machine list.
- The double rows should appear correctly and the menus should open on the rows.

## Fixes

Part of canonical-web-and-design/maas-squad/issues/2284.

### CODE REVIEW

**Review by Caleb-Ellis — APPROVED** [review]
LGTM!

**Comment by anthonydillon** [comment]
@huwshimi would it be trivial to copy this functionality to the ModularTable in React components?

**Comment by huwshimi** [comment]
> @huwshimi would it be trivial to copy this functionality to the ModularTable in React components?

The components are not very complex, but do contain a bunch of custom CSS. I'm not sure exactly how it would behave in ModularTable so might require a few changes, but probably doable. Do any other projects use the double row? If so might be nice for the CSS to become official Vanilla.

**Comment by anthonydillon** [comment]
That's exactly the path of the code. The CSS is moved to the React component library. Once merged. The styles are then ported to Vanilla. Once Vanilla is released, we follow up by cleaning up React components. 

No others projects use it at the moment but it's a task we will have to do at some point. So, I wondered if it was freshly converted. It would be quick to migrate to react components.

**Comment by huwshimi** [comment]
> That's exactly the path of the code. The CSS is moved to the React component library. Once merged. The styles are then ported to Vanilla. Once Vanilla is released, we follow up by cleaning up React components.
> 
> No others projects use it at the moment but it's a task we will have to do at some point. So, I wondered if it was freshly converted. It would be quick to migrate to react components.

Ah I see! I'll have quick look and see if it works with the modular table and if so I'll migrate it.

**Comment by huwshimi** [comment]
@anthonydillon it looks like these components can't just be dropped into ModularTable. It needs a bit of thought about how to generate the cells to be compatible with ModularTable.

**Comment by anthonydillon** [comment]
Ok thanks for looking into it @huwshimi

**Pull request merged**
