### PR TITLE
fix(ui) align the machine test table columns

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Align the machine test table columns

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to a machine details
- Go to Tests and see the tests table columns are better spaced

## Fixes
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/2196

### CODE REVIEW

**Comment by huwshimi** [comment]
@anthonydillon looks like a snapshot needs updating on this one.

**Comment by anthonydillon** [comment]
@huwshimi thanks, fixed

**Review by huwshimi — APPROVED** [review]
This looks better. I reckon it could do with some work at different sizes, but that could be a followup.

Screen Shot 2021-02-18 at 12 52 46 pm

**Comment by anthonydillon** [comment]
@huwshimi yeah for sure.

**Pull request merged**
