### PR TITLE
fix(legacy): update dnsresource on name change

### PR DESCRIPTION
**Pull request by squidsoup**
## Done
Resolve issue that resulted in a serverside crash when updating the name of a dns resource.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

* Create DNS record with name: "test-internal", type "A", value "1.2.3.4"
* Rename it to "test"
* Try to rename it back to "test-internal"
* Ensure the rename is successful, and the server does not return `list.remove(x): x not in list message will appear in UI`

* Rename a non A record (e.g. TXT)
* Ensure the rename is successful

## Fixes

Fixes: #1728 

## Launchpad issue

lp#1894894

## Backports

In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate releases to target.

Only bug and security fixes should be backported, new features should only land in master.

### CODE REVIEW

**Comment by huwshimi** [comment]
These were the different scenarios I tested:

For both an A or TXT record:
- rename to a previous name
- rename
- edit other values
- edit other values and name
- edit other values and rename to previous

### Issues:

For both an A or TXT record when editing only editing other values:
```
react_devtools_backend.js:2450 TypeError: Cannot read property 'then' of undefined
    at MAASFormController.saveForm (maas_obj_form.js?b750:278)
    at eval (maas_obj_form.js?b750:1145)
    at Scope.$eval (angular.js?41fa:19523)
    at Scope.$apply (angular.js?41fa:19622)
    at HTMLButtonElement.eval (maas_obj_form.js?b750:1144)
    at HTMLButtonElement.dispatch (jquery.js?a881:5429)
    at HTMLButtonElement.elemData.handle (jquery.js?a881:5233)
    at HTMLButtonElement.sentryWrapped (helpers.js?aabc:72) undefined
```

When renaming a TXT record the server responded with "DNSData matching query does not exist." which also flashed up in the bottom left of the form.

**Comment by squidsoup** [comment]
> For both an A or TXT record when editing only editing other values

Can you clarify what you mean by "when editing only editing other values"?

**Comment by huwshimi** [comment]
> > For both an A or TXT record when editing only editing other values
> 
> Can you clarify what you mean by "when editing only editing other values"?

Oh sorry, I mean when I edit other values in the form, but leave the name unchanged.

**Comment by huwshimi** [comment]
@squidsoup QA is good now! Do you think adding test is possible for this change?

**Comment by squidsoup** [comment]
> @squidsoup QA is good now! Do you think adding test is possible for this change?

There are actually no tests for *updating* DNS resources apparently, only creating and deleting. I can have a look.

**Review by huwshimi — APPROVED** [review]

**Pull request merged**
