### PR TITLE
fix(ui): fix DHCP docs link redirect

### LINKED ISSUE #3937: maas.io/docs links test failed on master
[maas.io/docs links test failed](https://github.com/canonical-web-and-design/maas-ui/actions/runs/2343198129) on the master branch.

### LINKED ISSUE #3943: maas.io/docs links test failed on renovate/internal
[maas.io/docs links test failed](https://github.com/canonical-web-and-design/maas-ui/actions/runs/2343124601) on the renovate/internal branch.

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Fixed DHCP docs link redirect

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Docs link test should pass

## Fixes

Fixes #3937
Fixes #3943

### CODE REVIEW

**Comment by huwshimi** [comment]
@Caleb-Ellis maybe I'm misunderstanding this fix, but aren't those runs failing for different urls?

**Comment by Caleb-Ellis** [comment]
@huwshimi huh... no you're not wrong. I think the docs link redirect check might be flaky - in some commits it's the DHCP link that fails, but in other commits it's the rack controller links that fails. I'll fix them both here and add an issue to investigate why it's not catching them all the time.

**Comment by Caleb-Ellis** [comment]
@huwshimi I've added an issue here: https://github.com/canonical-web-and-design/maas-ui/issues/3947

**Review by huwshimi — APPROVED** [review]
Looks good now!

**Pull request merged**
