### PR TITLE
Upgrade legacy vanilla

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done
- Updated legacy vanilla from v2.0.1 to v2.10.1
- Made footer sticky for react and angular apps
- Fixed a few styling things as drivebys:
  - Header strips now follow same format as react machine list (disable take action with tooltip unless some selected, text next to title = "1 of 2 devices selected" etc)
  - KVM details > Configuration tags input
  - KVM details > Compose form interface selection
  - Device details > Edit interface form table

## QA
- Check that the footer is sticky on the react and angular apps
- Click everything and navigate everywhere, there should hopefully be no styling regressions. Thankfully there are nowhere near as many changes as vanilla 1.8 or 2.0

## Fixes
Fixes canonical-web-and-design/MAAS-squad#1998
Fixes canonical-web-and-design/MAAS-squad#2000

### CODE REVIEW

**Comment by anthonydillon** [comment]
Code looks good. The tightness of the spacing looks much better now than before. 

## QA issues (connected to bolla):
On http://0.0.0.0:8400/MAAS/#/subnet/4 the form field needs col-4 not 3
image

When in Angular and moving from one section to another the selected item does not change.

Clicking on a machine in the machine list does not land you on the details

On http://0.0.0.0:8400/MAAS/#/machine/mpknwm?area=network. The checkbox is not at the top but not a blocker
image

**Comment by squidsoup** [comment]
> When in Angular and moving from one section to another the selected item does not change.
> 
> Clicking on a machine in the machine list does not land you on the details

@anthonydillon Those issues were fixed in my branch https://github.com/canonical-web-and-design/maas-ui/pull/1126 so this branch may just need to be rebased.

**Comment by squidsoup** [comment]
> > When in Angular and moving from one section to another the selected item does not change.
> > Clicking on a machine in the machine list does not land you on the details
> 
Ah looks like a different css-y issue:

```
Uncaught Error: application 'legacy' died in status LOADING_SOURCE_CODE: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: ".p-list--labelled" failed to @extend "%vf-list".
       The selector "%vf-list" was not found.
       Use "@extend %vf-list !optional" if the extend should be able to fail.
        on line 3 of src/scss/lists/_patterns_labelled-list.scss
>>     @extend %vf-list;

   ------------^
```

**Comment by squidsoup** [comment]
Oh actually, I can't replicate that after a clean build.

**Pull request merged**
