### PR TITLE
feat(ui): differentiate analytics events for list and details pages

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Send different category for GA events if in the details or list page
- Added test factories to a bunch of form test files that don't actually help with anything, but they're leftovers from when I did this PR wrong the first time. :D 

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- N/A

### CODE REVIEW

**Review by huwshimi — COMMENTED** [review]
@Caleb-Ellis what's the difference between these events and `onSaveAnalytics` in ActionForm? Does that one not fire at the right time?

**Comment by huwshimi** [comment]
@Caleb-Ellis it looks like these events aren't being sent. The event gets fired when saved becomes true in FormikForm, but it doesn't look like that prop is being passed from ActionForm.

**Comment by Caleb-Ellis** [comment]
Thanks @huwshimi that should be fixed now :+1:

**Review by huwshimi — APPROVED** [review]
Thanks @Caleb-Ellis!

**Pull request merged**
