### PR TITLE
Add power menu to machine list

### PR DESCRIPTION
**Pull request by huwshimi**
## Done
- Add the power menu to the machines in the machine list

## QA
- Visit /r/machines.
- In the power column you should see different actions depending on the current power state of the machine.

## Fixes
Fixes https://github.com/canonical-web-and-design/maas-squad/issues/1723.

### CODE REVIEW

**Comment by huwshimi** [comment]
Thanks @Caleb-Ellis, these should all be addressed except I've removed the spinner for checking power as we don't have a reliable way of knowing when the action is complete. Sound OK? Would you mind taking another look?

**Comment by huwshimi** [comment]
@Caleb-Ellis I've added this issue about the power checking: https://github.com/canonical-web-and-design/maas-ui/issues/781.

**Comment by Caleb-Ellis** [comment]
@huwshimi nevermind I see what the problem is now - there's no link between the update notify and the original check power request. In the angular version the result from the check power action mutates machine.power_state directly, which we probably shouldn't replicate hahaha.

**Comment by huwshimi** [comment]
Thanks @Caleb-Ellis

**Pull request merged**
