### PR TITLE
refactor(ui): update service to use a slice

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Replace the service reducers and actions with a slice.

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Load the machine list and check that the services were fetched (check the redux state in devtools)

## Fixes

Fixes: canonical-web-and-design/maas-ui#1410

### CODE REVIEW

**Comment by Caleb-Ellis** [comment]
@huwshimi Do you know why we fetch services in the machine list? Aren't they only needed for controllers?

**Comment by squidsoup** [comment]
> @huwshimi Do you know why we fetch services in the machine list? Aren't they only needed for controllers?
> 
> Pinging @squidsoup too in case you know

I can't see any reason to fetch `services` in the machine list.

**Comment by huwshimi** [comment]
> > @huwshimi Do you know why we fetch services in the machine list? Aren't they only needed for controllers?
> > Pinging @squidsoup too in case you know
> 
> I can't see any reason to fetch `services` in the machine list.

I've removed the fetch from the machine list.

**Comment by squidsoup** [comment]
> > > @huwshimi Do you know why we fetch services in the machine list? Aren't they only needed for controllers?
> > > Pinging @squidsoup too in case you know
> > 
> > 
> > I can't see any reason to fetch `services` in the machine list.
> 
> I've removed the fetch from the machine list.

Looks like a ts error:
```
  Line 42:21:  'serviceActions' is defined but never used  no-unused-vars
```

**Review by squidsoup — APPROVED** [review]
lgtm, just one lint issue to fixup.

**Comment by huwshimi** [comment]
> Looks like there's a ts error:
> 
> ```
>   Line 42:21:  'serviceActions' is defined but never used  no-unused-vars
> ```

Oops, thanks.

**Pull request merged**
