### PR TITLE
feat(ui) machine details instances table

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Build the machine details instances table

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch
You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Point your this branch as Karura
- Go to the machine "grand-amoeba"
- Switch to Instances tab
- Check it matches http://karura.internal:5240/MAAS/l/machine/qt7e3e?area=instances

## Fixes
Fixes: https://github.com/canonical-web-and-design/MAAS-squad/issues/2214

### CODE REVIEW

**Review by Caleb-Ellis — APPROVED** [review]
Nice work! :tada: 

This is pretty much good to go - I just have a couple of suggestions, which should also fix the TS strict mode errors.

One other thing - since this PR basically completes the Instances tab, you can update the Instances tab link in `MachineHeader.tsx` to point to the React version:

``` typescript
{
  active: pathname.startsWith(`${urlBase}/instances`),
  component: Link,
  label: "Instances",
  route: `${urlBase}/instances`,
},
```

**Comment by anthonydillon** [comment]
@Caleb-Ellis Thanks for the points. I have updated all the in code comments but I am unsure what you mean by the Tab link. I see that you have switched `to:` to `route: ` but I don't see that widely used and at the moment the instances tab when clicked opens the React version.

**Comment by Caleb-Ellis** [comment]
> @Caleb-Ellis Thanks for the points. I have updated all the in code comments but I am unsure what you mean by the Tab link. I see that you have switched `to:` to `route: ` but I don't see that widely used and at the moment the instances tab when clicked opens the React version.

Sorry, I didn’t explain it very clearly (and the code snippet might be wrong). Currently the Instances tab in machine details is a link to the angular page, but since this PR basically completes it, you might as well update it to be a link to the new React page.

**Comment by anthonydillon** [comment]
> Sorry, I didn’t explain it very clearly (and the code snippet might be wrong). Currently the Instances tab in machine details is a link to the angular page, but since this PR basically completes it, you might as well update it to be a link to the new React page.

Yeah, I thought that was what you meant but it already is. When in the React machine summary and you click the instances it loads the React instances tab.

**Comment by Caleb-Ellis** [comment]
> > Sorry, I didn’t explain it very clearly (and the code snippet might be wrong). Currently the Instances tab in machine details is a link to the angular page, but since this PR basically completes it, you might as well update it to be a link to the new React page.
> 
> Yeah, I thought that was what you meant but it already is. When in the React machine summary and you click the instances it loads the React instances tab.

Really? This is what I get on the React summary page when I pull this branch:

**Comment by anthonydillon** [comment]
@Caleb-Ellis thanks, all done

**Pull request merged**
