### PR TITLE
fix(ui): Native TLS QA fixes

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Fixed functionality of number input so clearing the field doesn't return 0
- Fixed styling of number input for older browsers
- Improved form validation

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Enable TLS for a MAAS (instructions [here](canonical-web-and-design/app-tribe#847))
- Go to Settings > Security
- Enable notifications and clear the number input
- Check that an error shows up
- Uncheck the notifications checkbox and check that you can submit the form, even with an invalid interval value

## Fixes

Fixes canonical-web-and-design/app-tribe#847

### CODE REVIEW

**Comment by huwshimi** [comment]
If I enter an invalid value (e.g. 1000) and then save it works, but then if I click the checkbox again to enable it the save button is disabled, but the error doesn't reappear for the invalid value.

**Comment by Caleb-Ellis** [comment]
@huwshimi ok that should be fixed now - was in issue with `resetForm()` resetting the errors

**Review by huwshimi — APPROVED** [review]
This works now. One other thing I noticed was that when the input is cleared then the blue bar and the handle are out of sync:

Screen Shot 2022-05-26 at 5 15 13 pm

**Comment by Caleb-Ellis** [comment]
@huwshimi hmm I think that must be a Chrome thing, since the blue bar is calculated with JS for webkit browsers. I'll file a bug in react-components to be able to handle clearing the field

**Pull request merged**
