### PR TITLE
add formik-devtools-extension

### PR DESCRIPTION
**Pull request by petermakowski**
## Done

- add formik-devtools-extension https://www.npmjs.com/package/formik-devtools-extension
- it can make easier to debug issues with forms

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Install the extension using instructions here: https://www.npmjs.com/package/formik-devtools-extension
- open formik devtools via chrome/firefox developer tools
- Go to `/MAAS/r/networks?by=fabric`
- select "Add VLAN"
- verify formik state updates appear in the extension

## Fixes

Fixes: # .

## Launchpad issue

Related Launchpad maas issue in the form `lp#number`.

## Backports

In general, please propose fixes against *master* rather than release branches (e.g. 2.7), unless the fix is only applicable for that specific release. Please apply backport labels to the PR (e.g. "Backport 2.7") for the appropriate releases to target.

Only bug and security fixes should be backported, new features should only land in master.

### CODE REVIEW

**Comment by anthonydillon** [comment]
@petermakowski could you provide more information about the extension and detailed QA steps.

**Comment by petermakowski** [comment]
> @petermakowski could you provide more information about the extension and detailed QA steps.

Sure!

**Comment by petermakowski** [comment]
> @petermakowski could you provide more information about the extension and detailed QA steps.

Done 🙏

**Review by Caleb-Ellis — APPROVED** [review]
LGTM!

**Pull request merged**
