### PR TITLE
ci(ci): run actions against the 2.9 branch

### PR DESCRIPTION
**Pull request by huwshimi**
## Done

- Run CI against the 2.9 branch.

### CODE REVIEW

**Review by anthonydillon — COMMENTED** [review]
I wonder if we should use wildcarded tags? https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

**Comment by huwshimi** [comment]
I think I need to update the other workflows as well.

**Comment by huwshimi** [comment]
> I wonder if we should use wildcarded tags? https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

I think we want it set to a specific branch as we don't want to run the actions defined in one branch to be run against a different branch.

**Comment by huwshimi** [comment]
This one is ready for review now.

**Review by Caleb-Ellis — APPROVED** [review]

**Pull request merged**
